### ISSUE TITLE
How to install？

### ISSUE THREAD

**Issue by aomiks** [madtunebk/ComfyUI-ControlnetAux#1]
File "E:\AAAComfyUI\ComfyUI\custom_nodes\ComfyUI-ControlnetAux\controlnetaux.py", line 1, in <module>
    from controlnet_aux.processor import Processor
ModuleNotFoundError: No module named 'controlnet_aux'

Cannot import E:\AAAComfyUI\ComfyUI\custom_nodes\ComfyUI-ControlnetAux module for custom nodes: No module named 'controlnet_aux'

**Comment by madtunebk** [comment]
Apologies, on Ubuntu Linux, my node seems to automatically fetch requirements. I'll include the requirements.txt file. It appears you're missing the controlnet_aux Python package.

**Comment by aomiks** [comment]
After installing the dependencies of controlnet_aux0.07, this [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux) node prompts:

[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because ImportError: cannot import name 'DwposeDetector' from 'controlnet_aux.dwpose' (D:\Programs\anaconda3\envs\comfyui\Lib\site-packages\controlnet_aux\dwpose\__init__.py)

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)

Do these two conflict with each other?

**Comment by madtunebk** [comment]
DwposeDetector' has been removed from my node. I will add it soon after fixing options for all ControlNet modules. The current models that are working are: 
models = ["scribble_hed", "softedge_hed", "scribble_hedsafe", "softedge_hedsafe", "depth_midas", "openpose",
           "openpose_face", "openpose_faceonly", "openpose_full", "openpose_hand", "scribble_pidinet",
           "softedge_pidinet", "scribble_pidsafe", "softedge_pidsafe", "normal_bae", "lineart_coarse",
           "lineart_realistic", "lineart_anime", "depth_zoe", "depth_leres", "depth_leres++", "shuffle",
           "mediapipe_face", "canny"]

**Comment by aomiks** [comment]
It may be that the DWpose in the ComfyUI-ControlnetAux node conflicts with the dependencies of controlnet_aux.

**Comment by aomiks** [comment]
It's not a problem with your CNaux, it should be a problem with the CN_aux node. CN_aux may be using the library functions brought by its own node, resulting in a conflict with the dependent library functions of ctrolnet_aux.

**Comment by madtunebk** [comment]
Done, please check. DWpose works on Linux Ubuntu.

**Comment by madtunebk** [comment]
After I read a little more, I found that the 'controlnet_aux' uses DWpose, which requires some additional Python packages to be installed outside of the pip manager. These packages include 'mmengine', 'mmcv>=2.0.1', 'mmdet>=3.1.0', and 'mmpose>=1.1.0'. Perhaps this is why it fails to use DWpose by default. However, I managed to get it working by installing those packages manually

**Comment by aomiks** [comment]
These dependencies I have already installed, but DWpose still has problems. It should be that the author of controlnet_aux needs to update the code of this dependency. The default is to use the dependencies in the controlnet_aux directory under the Comfyui_controlnet_aux node. Installing [python](coco://sendMessage?ext=%7B%22s%24wiki_link%22%3A%22https%3A%2F%2Fm.baike.com%2Fwikiid%2F5288202461300639511%22%7D&msg=python)'s controlnet_aux causes DWpose to give priority to calling this library, resulting in compatibility issues. Thank you! You are very dedicated and have a great spirit of sharing! Great!

**Comment by madtunebk** [comment]
I don't own the Controlnet_aux or Comfyui_controlnet_aux, so I don't know how to help you in your case. My custom node, ComfyUI-ControlnetAux, works just fine. Just follow the installation instructions or search for it in the ComfyUI manager.
